#include "VrabApp.h"
#include "Moose.h"
#include "AppFactory.h"

template<>
InputParameters validParams<VrabApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  return params;
}

VrabApp::VrabApp(const std::string & name, InputParameters parameters) :
    MooseApp(name, parameters)
{
  srand(processor_id());

  Moose::registerObjects(_factory);
  VrabApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  VrabApp::associateSyntax(_syntax, _action_factory);
}

VrabApp::~VrabApp()
{
}

// External entry point for dynamic application loading
extern "C" void VrabApp__registerApps() { VrabApp::registerApps(); }
void
VrabApp::registerApps()
{
  registerApp(VrabApp);
}

// External entry point for dynamic object registration
extern "C" void VrabApp__registerObjects(Factory & factory) { VrabApp::registerObjects(factory); }
void
VrabApp::registerObjects(Factory & factory)
{
}

// External entry point for dynamic syntax association
extern "C" void VrabApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { VrabApp::associateSyntax(syntax, action_factory); }
void
VrabApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}
